name: Bug Report
description: Report incorrect behavior in the tmlt.analytics library
title: "BUG: "
labels: [Bug, Needs Triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Basic checks
      options:
        - label: >
            I can confirm that there isn't a seperate issue filed related to this bug.
          required: true
        - label: >
            I can reproduce this bug on the [latest version]
            (https://tmlt.dev/analytics/latest/changelog.html of tmlt.analytics.
          required: true
  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: >
        Please add an example that reproduces the bug.
        
        [This guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) has guidance
        on how to create an example.
      placeholder: >
        from pyspark.sql import SparkSession
        from tmlt.analytics import Session, PureDPBudget, AddOneRow

        spark = SparkSession.builder.appName("example").getOrCreate()
        df = spark.createDataFrame(
            [(1, "Alice"), (2, "Bob")],
            ["id", "name"]
        )

        session = Session.Builder() \
          .with_private_dataframe("example", df, AddOneRow()) \
          .with_privacy_budget(PureDPBudget(1)) \
          .build()
        ...
      render: python
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Bug Description
      description: >
        Please describe the bug, specifically the undesirable behavior, shown by your example.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: >
        Please describe what the exepected program outputs of your example code are.
    validations:
      required: true
