name: Installation Issue
description: Report issues installing tmlt.analytics.
labels: [Install, Needs Triage]

body:
  - type: input
    id: platform
    attributes:
      label: Platform
      description: >
        Please describe the system you're trying to install on.
        
        Import notes for tmlt.analytics: 
         - What versions of Java, Python, and Spark do you have installed?
         - What processor architecture (ex: x86_64 or arm) are you installing on?
         - What operating system and version are you installing on?
         - What version of tmlt.core are you using?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Installation Issue
      description: >
        Please describe the current issue you're having. Add relevant error messages and logs.
      value: >
        - Describe the issue here.
        - Add relevant error messages.
        - Replace this line with the installation logs.
