name: Performance Issue
description: Report slow runtime performance or memory use errors.
title: "Performance: "
labels: [Performance, Needs Triage]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Basic checks
      options:
        - label: >
            I can confirm that another issue hasn't been filed for this problem.
          required: true
        - label: >
            I can reproduce this bug on the [latest version]
            (https://tmlt.dev/analytics/latest/changelog.html of tmlt.analytics.
          required: true
  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: >
        Please add an example that reproduces the bug.
        
        [This guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) has guidance
        on how to create an example.
      placeholder: >
        from pyspark.sql import SparkSession
        from tmlt.analytics import Session, PureDPBudget, AddOneRow

        spark = SparkSession.builder.appName("example").getOrCreate()
        df = spark.createDataFrame(
            [(1, "Alice"), (2, "Bob")],
            ["id", "name"]
        )

        session = Session.Builder() \
          .with_private_dataframe("example", df, AddOneRow()) \
          .with_privacy_budget(PureDPBudget(1)) \
          .build()
        ...
      render: python
    validations:
      required: true
  - type: textarea
    id: prior-performance
    attributes:
      label: Prior Performance
      description: >
        If an earlier version of tmlt.analytics didn't have this performance issue,
        provide the relevant version numbers.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: >
        If this is not a performance issue with the newest version of tmlt.analytics,
        please describe what the performance issue is.